services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    environment:
      # Make sure to add an NGROK_AUTHTOKEN to .env, or the environment of the host
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["http", "--url=${NGROK_URL}", "--log=stdout", "http://veramo-agent:3000"]
    ports:
      - 4040:4040 # diagnostics and management UI
    networks:
      - eduwallet_agent
      - shared-network

  veramo-agent:
    build:
      context: .
    container_name: veramo-agent
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - "db:db"
      - "log:log"
    volumes:
      - .:/app:ro
      - /dev/null:/app/.env:ro # Ensure we don't use the host's .env file but set env vars explicitly
      - ./conf:/conf:ro
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=this-is-not-secure
      - DB_NAME=postgres
      - DB_SCHEMA=agent
      - CONF_PATH=/conf
      - DEBUG=*
      - DEBUG_DEPTH=10
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eduwallet_agent
      - shared-network

  db:
    image: postgres:16-bookworm
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=this-is-not-secure
      - POSTGRES_DB=postgres
    volumes:
      - type: bind
        source: /tmp/database
        target: /var/lib/postgresql/data
      - type: bind
        source: ./scripts/dbinit
        target: /docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      retries: 5
      start_period: 1s
      timeout: 5s
    ports:
      - "5432:5432" 
    networks:
      - eduwallet_agent

  log:
    image: public.ecr.aws/zinclabs/openobserve:latest
    hostname: log
    restart: unless-stopped
    ports:
      - 5080:5080
    volumes:
      - type: bind
        source: /tmp/log/
        target: /data
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=info@muisit.nl
      - ZO_ROOT_USER_PASSWORD=me:topsecret
      - ZO_INGEST_FLATTEN_LEVEL=1
    networks:
      - eduwallet_agent

networks:
  shared-network:
    external: true
  eduwallet_agent:
    driver: bridge
